In [1]:
import numpy as np
import pickle

In [13]:
b = np.load("dataset_random_384/board_pos_0.npy")

print(b)

[[-1  0  0  1  0 -6  0  0]
 [ 0  0  0  6  0  1 -1 -1]
 [ 3 -3  2  0  5  1  0  0]
 [ 0  0 -2 -1  1  0  1 -4]
 [ 0  0  0  0  0  0 -1  0]
 [-1  0  0  4 -2  0  3  0]
 [-1  0  0  0 -5  0 -1 -3]
 [-4  1  1  2  0  4  1  0]]


In [82]:
# a = np.load("chess_arrays_mini.npy")
# a = np.load("4_1_mini_random_change.npy")
# a = np.load("4_1_random_changed.npy")
# a = np.load("actual_lm.npy")
# a = np.load("random_41_full.npy")
# a = np.load("random_mini_v2.npy")
# a = np.load("qwen25_384_eval.npy")
# a = np.load("qwen_7b_v7.npy")
# a = np.load("qwen_7b_notrain.npy")
# a = np.load("qwen_eval_128.npy")
a = np.load("pixtral_board_final.npy")

In [83]:
print(a.shape)
a = a[:128]
print(a.shape)

(129, 8, 8)
(128, 8, 8)


In [84]:
def eval_strict(out, board_pos):

    #! Only reward if non zero entries match. First find the total non zero entries in board_pos (which is ground truth).
    # Create a boolean mask for non-zero elements in board_pos
    non_zero_mask = board_pos != 0

    # If there are no non-zero elements in board_pos, return 1.0 (or handle as appropriate)
    if not np.any(non_zero_mask):
        return 1.0  # Or 0.0, or raise an error, depending on desired behavior

    # Compare elements of out and board_pos where board_pos is non-zero
    correct_matches = out[non_zero_mask] == board_pos[non_zero_mask]

    # Calculate accuracy
    accuracy = np.mean(correct_matches)
    
    return accuracy


In [88]:
dataset_path = "dataset_random_384/"
total = 0
for i in range(128):

    board_pos_path = f"{dataset_path}/board_pos_{i}.npy"
    board_pos = np.load(board_pos_path)

    total += eval_strict(a[i], board_pos)
    
print(total/128)    

1.0


In [ ]:
#mini -> 0.787361676844295
#full -> 0.6776969567408736

#mini random -> 0.56884765625
#full random -> 0.269 (!! WHAT ??)

#Pixtral -> 0.041259765625  (LOL!!!)
#Pixtral v2 -> 0.045166015625

#llama 13 b vision -> 0.019 


#constant -> 0.556 (non random dataset)

#smolvlm (random dataset) -> 0.072998046875 (slightly different)
#constant (random dataset) -> 0.0729 

#llava -> 0.0 (after SFT)

#Train on the dataset -> 0.076904296875

In [7]:
# print(a[0])

[[ 0  0 -6  0  0  0  0 -4]
 [-1  0 -3  0  0  0 -1 -1]
 [ 0 -1  0  0  0  0  0 -1]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0 -4  0  0 -2  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  1  0  1  0  1  0  1]
 [ 4  2  3  0  5  3  2  4]]


In [4]:
import pickle

# data = [['hello', 'world'], ['test', 'pickle']]

# with open('data.pkl', 'wb') as f:
#     pickle.dump(data, f)

# Load
with open('best_moves_128_with_matrix/best_moves.pkl', 'rb') as f:
    loaded_data = pickle.load(f)

with open('best_moves_128_with_matrix/color.pkl', 'rb') as f:
    color_data = pickle.load(f)



In [5]:
loaded_data[0][0]

'b4'

In [77]:
# with open('best_41_full_color_correct.pkl', 'rb') as f:
#     filtered_data = pickle.load(f)
#qwen_best.pkl

with open('smol_vlm_best.pkl.pkl', 'rb') as f:
    filtered_data = pickle.load(f)


In [78]:
# print(list(set(filtered_data)))
# print(len(list(set(filtered_data))))

counts = {x: filtered_data.count(x) for x in set(filtered_data)}
print(counts)

{'d5': 102, 'e5': 2, 'd4': 18, 'e4': 6}


In [70]:
a = []
for gt in loaded_data:
    a.append(gt[0])
    # if gt[0] == 'd5':
    

counts = {x: a.count(x) for x in set(a)}
print(counts)

{'Nc6': 1, 'Rh7': 1, 'Bxd3': 1, 'Nxe5': 1, 'dxe5': 2, 'f4': 1, 'Bb4': 1, 'Nb4': 1, 'Nxc6': 1, 'Qxc3': 1, 'Qe3': 1, 'b4': 2, 'Rxa5': 2, 'Nf6': 3, 'Nd4+': 1, 'Bxd7': 1, 'e4': 9, 'Bxb5': 1, 'bxa5': 1, 'Qd7': 1, 'Nxe4': 1, 'Bxd4': 1, 'Qxh7': 1, 'Nxg5': 1, 'Nd6': 1, 'Nd7': 1, 'Be7': 1, 'g4': 1, 'Bxg5': 2, 'Nxb5': 1, 'Rb5': 1, 'Bg7': 2, 'Nxh6': 1, 'Nxd8+': 1, 'Nf4': 1, 'Nxf2': 1, 'exf7+': 1, 'e5': 6, 'Bxc1': 1, 'Bxf4': 1, 'Nxb6': 1, 'Rxe4+': 1, 'hxg3': 1, 'Nd2': 1, 'hxg5': 1, 'Bxe7': 1, 'f5': 1, 'Qxc2': 2, 'Qxe4': 1, 'Qxf2#': 1, 'Bg2': 1, 'exf4': 1, 'a6': 1, 'Qg7': 1, 'hxg4': 1, 'd5': 2, 'Nxa6': 2, 'Bxh3': 1, 'Qxe5+': 1, 'fxe5+': 1, 'bxa3': 1, 'Bxb2': 1, 'Kxf7': 1, 'Bxg7': 1, 'cxd5': 1, 'c5': 1, 'cxd3': 2, 'Qb3+': 1, 'Qxg4+': 1, 'Qc8': 1, 'Kxc8': 1, 'cxb5': 1, 'd4': 3, 'g5': 2, 'dxe4': 1, 'Na6': 1, 'exd6': 1, 'd6': 1, 'bxc3': 1, 'Kxf8': 1, 'Qxd5': 1, 'Nxa3': 1, 'Bxd6': 1, 'c2': 1, 'a4': 1, 'Rxg5': 1, 'O-O': 1, 'Rf8': 1, 'hxg6': 1, 'c6': 2, 'Nxh7': 1, 'Rxa3': 1, 'Nf3': 2, 'Kf2': 1, 'Qc2': 1, 

In [79]:
new_filtered_data = filtered_data[:-1]

In [80]:
print(new_filtered_data)

['d5', 'd5', 'e4', 'd4', 'd5', 'd5', 'd5', 'd5', 'd5', 'd4', 'd5', 'd5', 'd5', 'e5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'e4', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd4', 'd5', 'd5', 'd4', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd4', 'd5', 'd5', 'd4', 'd5', 'd5', 'd4', 'd5', 'd5', 'd5', 'd5', 'd4', 'd4', 'd5', 'd5', 'd4', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd4', 'd5', 'e4', 'd5', 'd5', 'd5', 'd4', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd4', 'd5', 'd4', 'd5', 'd5', 'd5', 'd4', 'd5', 'd5', 'd5', 'd5', 'e4', 'd5', 'd5', 'd5', 'd5', 'd4', 'd5', 'd4', 'd5', 'd5', 'e4', 'e5', 'd4', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'd5', 'e4', 'd5', 'd5', 'd5']


In [81]:


correct = 0
for i in range(len(new_filtered_data)):
    my_prediction = new_filtered_data[i]
    gt_preds = loaded_data[i]

    # print(gt_preds[:2])
    if my_prediction in gt_preds[:10]:
        print(my_prediction, gt_preds[:3])
        correct += 1

print(len(new_filtered_data))
print(correct/len(new_filtered_data))

d5 ['b4', 'd5', 'h5']
e4 ['e4', 'd4', 'Nf3']
d5 ['d5', 'Nf6', 'e6']
d5 ['a6', 'c6', 'b4']
d5 ['e5', 'Nf6', 'd5']
d5 ['e5', 'Nf6', 'd5']
d5 ['bxa3', 'Be7', 'Bc5']
d5 ['c2', 'c6', 'exd3']
d5 ['Kxf8', 'Ne6', 'd6']
e4 ['e4', 'd4', 'g3']
d5 ['e5', 'd5', 'Nc6']
d4 ['e4', 'Nc3', 'Nf3']
d5 ['c5', 'e5', 'Nf6']
d5 ['g6', 'hxg4', 'e6']
d5 ['hxg4', 'e5', 'd5']
d5 ['cxd3', 'Na6', 'd5']
d4 ['Nxb5', 'e4', 'Nf3']
d4 ['Bxf4', 'gxh5', 'e3']
d5 ['Nc6', 'd5', 'h6']
d5 ['e5', 'h5', 'd6']
d5 ['Bg7', 'Nf6', 'Qa5+']
d5 ['exf4', 'h4', 'd5']
d5 ['Qxe4', 'Ra7', 'd5']
d5 ['Nf6', 'fxe4', 'e5']
d5 ['f5', 'fxg5', 'hxg5']
d5 ['g4', 'a5', 'h6']
e4 ['e4', 'd4', 'Nf3']
d4 ['Nxd8+', 'Bxc5', 'Na3']
d5 ['Nc5', 'd5', 'Rh8']
d4 ['Bxb5', 'Nxb5', 'Qf3']
d5 ['Nxa6', 'Bxa6', 'Kf7']
e4 ['e4', 'd4', 'Nf3']
d5 ['d5', 'Nf6', 'Nc6']
d5 ['e5', 'c5', 'Nf6']
d4 ['d4', 'g3', 'd3']
e4 ['e4', 'd4', 'e3']
d5 ['Qc8', 'Bg7', 'Qf6']
e4 ['e4', 'd4', 'Nf3']
127
0.2992125984251969


In [11]:
print(new_filtered_data)

['Nf7', 'e3', 'd4', 'bxc5', 'Nxa3', 'd5', 'e5', 'Nf3', 'fxg5', 'Nxb5', 'Nxb5', 'd5', 'Nxf7', 'Bxg5', 'g5', 'd5', 'Ke1', 'e4', 'Bb7', 'bxc4', 'd5', 'Nf6', 'cxd4', 'Ke1', 'cxd4', 'Nxd1', 'e4', 'Bxd7', 'd4', 'Nxd1', 'fxg5', 'Nf3', 'd5', 'fxg4', 'Nxd1', 'Qh4', 'e4', 'd5', 'exd5', 'e5', 'Qf5', 'Be2', 'Nxb5', 'g4', 'fxg4', 'd5', 'b4', 'Nxd1', 'fxg4', 'g5', 'Qxe4', 'Bxh3', 'Ng3+', 'd5', 'fxg4', 'Bxh3', 'fxg5', 'Qh4', 'g5', 'Bxg5', 'Bxd7', 'Be2', 'Bxa3', 'fxg5', 'e5', 'Bb7', 'fxg4', 'Be2', 'Nf3', 'e5', 'b4', 'Nf7', 'Bxa3', 'cxd4', 'Qxf4', 'Bxe7', 'Bb7', 'Nxd1', 'fxg4', 'fxe4', 'd4', 'exd5', 'Kd2', 'Nf3', 'Qxd8', 'exd5', 'Qxe4', 'Qxf4', 'Bxd7', 'e5', 'e4', 'Qxe4', 'Nxd1', 'Qxe4', 'Ng3+', 'e5', 'cxd4', 'g5', 'Qh4', 'Qb1+', 'Nxf3+', 'Ke1', 'd4', 'd5', 'Bb7', 'Nxd1', 'Qxd8', 'Nf3', 'd5', 'Nf3', 'Nxd1', 'Qf5', 'd4', 'Qb5', 'Bxa8', 'Nxa3', 'Bb7', 'Nxd3', 'exd5', 'Bb7', 'e5', 'Bb7', 'fxg5', 'd4', 'Qh4', 'hxg5', 'Nxa3', 'Bb7']


In [12]:


correct = 0
for i in range(len(new_filtered_data)):
    my_prediction = new_filtered_data[i][0]
    gt_preds = loaded_data[i]

    # print(gt_preds[:2])
    if my_prediction in gt_preds[:10]:
        correct += 1

print(len(new_filtered_data))
print(correct/len(new_filtered_data))

128
0.0
